### ISSUE TITLE
[C#] Multi-Lingual Sample fails with 4.2 Preview Builds

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder-Samples#1050]
As part of regression testing of the 4.2 release, @jwiley84 found the following bug:

```
Microsoft.BotBuilderSamples.MultiLingualBot:Error: Exception caught : Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Microsoft.BotBuilderSamples.Translation.Model.TranslatorResponse[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 1, position 9.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.BotBuilderSamples.Translation.MicrosoftTranslator.<TranslateAsync>d__6.MoveNext() in C:\Users\v-jewail\Desktop\regtest\BotBuilder-Samples\samples\csharp_dotnetcore\17.multilingual-bot\Translation\MicrosoftTranslator.cs:line 47

```

**Comment by jwiley84** [comment]
...It helps if you remember to put the key in the appsettings file. That being said, that error message could have been MUCH clearer.

**Comment by jwiley84** [comment]
A quick repro shows that if the key is blank, you get an appropriate error to update the key. If the key is INCORRECT (the sample comes with <Your translation key here> in the appsettings file), you get the above message.
