### ISSUE TITLE
 TypeError: Swagger.ApiKeyAuthorization is not a constructor

### ISSUE THREAD

**Issue by vgoyal1996** [Microsoft/BotBuilder-Samples#151]
I am trying to run the app.js file in the DirectLineClient folder in Node.js in accordance with the documentation provided. But I am getting the following error while authorizing the api key.
![error](https://user-images.githubusercontent.com/12955559/27422063-81d2c95c-574a-11e7-8dd0-62b9970660af.png)
I am getting this error in line 21 of the following code snippet.
![snippet](https://user-images.githubusercontent.com/12955559/27422300-3a51c866-574b-11e7-93c2-7d7c3a6392a5.png)
I searched a lot about a solution to this error but could not find anything. Any help is appreciated.

**Comment by aarrotta** [comment]
Same issue here with a custom JS client generated using swagger:
```
[Viewport]: Error: TypeError: BackendService.TokenApi is not a constructor: Name: TypeError: BackendService.TokenApi is not a constructor
Error message: Uncaught TypeError: BackendService.TokenApi is not a constructor
File name: Modules/Backend.js
Line number: 21
Source line: 	var tokenApi = new BackendService.TokenApi();
JS stack trace: TypeError: BackendService.TokenApi is not a constructor
    at Object.authenticateAdmin (Modules/Backend.js:21:17)
    at Object.authenticateAdmin (Modules/Context.js:30:17)
    at OnTapContinue (Pages/LoginAdminPage.ux:19:24)
 in Fuse.Reactive.FunctionMirror<Modules/Backend.js:21>
```

**Comment by jinot92** [comment]
I has a similar issue(client wasnt getting initialized).I changed the swagger-client version to the version mentioned in the sample. That fixed my problem.

**Comment by EricDahlvang** [comment]
This sample can now be found here: https://github.com/Microsoft/BotBuilder-Samples/blob/v3-sdk-samples/Node/core-DirectLine/DirectLineClient/package.json  It is using swagger-client 2.1.18 and works as expected.
