### ISSUE TITLE
[Bug] Node/core-GetConversationMembers example doesn't work

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder-Samples#154]
I'm trying to test the code example `Node/core-GetConversationMembers` but it fails on localhost + Emulator with the following error:

```js
> node app.js

restify listening to http://[::]:3978
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
UniversalBot("*") routing "hi" from "emulator"
Session.beginDialog(/)
/ - waterfall() step 1 of 1
Error retrieving conversation members { Error: Refresh access token failed with status code: 401
    at Request._callback (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/botbuilder/lib/bots/ChatConnector.js:550:28)
    at Request.self.callback (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  cause:
   Error: Refresh access token failed with status code: 401
       at Request._callback (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/botbuilder/lib/bots/ChatConnector.js:550:28)
       at Request.self.callback (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/request/request.js:188:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:191:7)
       at Request.<anonymous> (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/request/request.js:1171:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at IncomingMessage.<anonymous> (/Users/nw/src/_microsoft/BotBuilder-Samples/Node/core-GetConversationMembers/node_modules/request/request.js:1091:12)
       at IncomingMessage.g (events.js:291:16)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickDomainCallback (internal/process/next_tick.js:128:9),
  isOperational: true }
/ - Session.sendBatch() sending 0 message(s)
```

What am I doing wrong? Does this sample require additional configuration to run correctly?

**Comment by EricDahlvang** [comment]
GetConversationMembers is working against the V4 emulator.
