### ISSUE TITLE
Unable to authenticate Bot through Teams using JavaScript SDK 

### ISSUE THREAD

**Issue by mattchilds1** [microsoft/BotBuilder-Samples#1637]
## Sample information

1. Sample type: Samples
2. Sample language: nodejs
3. Sample name: 18.bot-authentication & 24.bot-authentication-msgraph

## Describe the bug

When deploying both of these samples they work with the bot emulator, but not through Teams.

Working:

```
- Bot served locally using restify (node v10.15.3)
- Bot emulator (latest on osx)

```

Not Working:

```
- Bot served on AWS Lambda (node v10.x)
- Bot on Azure Bot Registry and loaded as an App into Microsoft teams

```

## To Reproduce

1. Say hello to auth bot
2. Click on 'Sign in'
3. Log into Azure AD account on popup

## Expected behavior

At this point we would expect to see

```
Hello and welcome!

You are now logged in.

Would you like to view your token?

```

on both teams and the bot emulator.

## Error messages

Currently whilst running this through teams we are seeing the error message as a user after going through the sign in process:
"Unable to sign in. Please try signing in again."
and this in our logs:

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read property 'toString' of undefined",
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'toString' of undefined",
        "    at process.on (/var/runtime/index.js:29:13)",
        "    at process.emit (events.js:189:13)",
        "    at process.EventEmitter.emit (domain.js:441:20)",
        "    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)",
        "    at process._tickCallback (internal/process/next_tick.js:69:34)"
    ],
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read property 'toString' of undefined",
        "stack": [
            "TypeError: Cannot read property 'toString' of undefined",
            "    at BotFrameworkAdapter.processActivity (/var/task/node_modules/botbuilder/lib/botFrameworkAdapter.js:505:91)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
        ]
    },
    "promise": {}
}
```

## Additional context

This error message we see seems to be related to other issues raised on this bot samples repository, which are all around the dotnet core samples.

Is it possible that the [fix] (seen below)(https://github.com/microsoft/BotBuilder-Samples/commit/2412f237a5b999cddffbebd4d7e6ef159e6faf53), which has been put in place for dotnet core is infact a patch on the sample which should fix somwething core in the API / SDK?

https://github.com/microsoft/BotBuilder-Samples/commit/2412f237a5b999cddffbebd4d7e6ef159e6faf53

```
if (turnContext?.Activity?.Type == ActivityTypes.Invoke && turnContext.Activity.ChannelId == "msteams")
    await Dialog.Run(turnContext, ConversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);
```

**Comment by jwiley84** [comment]
Have you tried the new sample, #46? It specifically demonstrates oauth in teams.

**Comment by johnataylor** [comment]
We are currently fixing issues and showing features for Teams by adding Teams specific samples. Auth is slightly different for Teams because it sends an Invoke. It actually sends a bunch of different Invokes for different scenarios. And we will add more samples showing that.

So for now please look at the Teams.Auth sample.

**Comment by johnataylor** [comment]
Sorry I seemed to have broken the link @jwiley84 forwarded by renaming the sample. Here is a new link:

https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth

**Comment by mattchilds1** [comment]
The new sample is now working, thanks both!
