### ISSUE TITLE
Getting an Sorry no registered Luis and Qna Found error 

### ISSUE THREAD

**Issue by NikhilBansal21** [microsoft/BotBuilder-Samples#1659]
## Sample information
1. Sample type: nlp dispatch
2. Sample language: [dotnetcore 
3. Sample name: nlp dispatch

## Describe the bug
On following microsoft's  url for creating a dispatch for QnA and Luis and creating a Luis app for both, On configuring app_settings.json with luis and qna's credentials . When i run my bot on emulator i am getting following error -

**---------------------------------------------------------------------------------------------**
System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found —> System.Net.Sockets.SocketException: The requested name is valid, but no data of the requested type was found

at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

— End of inner exception stack trace —

at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.AI.Luis.LuisDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisDelegatingHandler.cs:line 31

at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

at Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime.Prediction.ResolveWithHttpMessagesAsync(String appId, String query, Nullable1 timezoneOffset, Nullable1 verbose, Nullable1 staging, Nullable1 spellCheck, String bingSpellCheckSubscriptionKey, Nullable1 log, Dictionary2 customHeaders, CancellationToken cancellationToken)

at Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime.PredictionExtensions.ResolveAsync(IPrediction operations, String appId, String query, Nullable1 timezoneOffset, Nullable1 verbose, Nullable1 staging, Nullable1 spellCheck, String bingSpellCheckSubscriptionKey, Nullable`1 log, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeInternalAsync(ITurnContext turnContext, Dictionary2 telemetryProperties, Dictionary2 telemetryMetrics, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisRecognizer.cs:line 295

at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeAsync(ITurnContext turnContext, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisRecognizer.cs:line 150

at Microsoft.BotBuilderSamples.DispatchBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in F:\nikhil\Alfi\mts-qna+luis\Bots\DispatchBot.cs:line 29

at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 964

at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55

at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167
**------------------------------------------------------------------------------------------**

## Expected behavior
Here i am expecting that bot must reply with intent or QnA reply of the individual input provided

**Comment by mdrichardson** [comment]
I wasn't able to replicate this and can run the Dispatch sample without errors. Looking at your stack trace, I think we can narrow this down to LUIS (maybe). Can you verify:

1. Your `appsettings.json` uses the Dispatch LUIS App's appId, and not one of the Weather or Home Automation ones
2. Both Weather and Home Automation are published
3. In `appsettings.json`, what do you have for `LuisAPIHostName` and `QnAEndpointHostName`?
4. Are you behind any kind of restricted DNS or Firewall?
5. Are you still experiencing this issue (maybe it was temporary outage)?
6. Can you share your LUIS AppIds?

**Comment by leoskvl** [comment]
Hi, I am new in using BotBuild and getting the same issue when testing my bot via Bot Emulator.

![image](https://user-images.githubusercontent.com/13193576/61505938-1f6f5000-aa13-11e9-86f7-116da408e29a.png)

-- appsettings.json consist of LUIS Dispatch app id and QnaMaker ID
-- botemulator.bot settings consist of 2 Luis Model settings, qnamaker settings and LUIS Dispatch settings.

Thanks!

**Comment by NikhilBansal21** [comment]
hi

1- i am passing my Dispatch luis's appd id and not the one's of weather and Home automation one
2- by weather and home apps published , you mean from luis when we publish our apps on azure ?
3- luis host name - westus.api.cognitive.microsoft.com and
 qna - https://mts-qna.azurewebsites.net/qnamaker
4- i was but my team have disabled firewall and dns restrictions for my system
5- luis app id for dispatch model - 3a817f48-0f1c-41d0-83aa-23f577639696
luis app id for my behind the scene luis model (like weather / home luis model)  -
db79a7ba-8555-44c7-b52e-d88800df4200

**Comment by NikhilBansal21** [comment]
@leoskvl  better debug the code , as this message comes only when their is some kind of exception, try looking into AdapterWithErrorHandler class  their you can log the exception or you can put a break point over there, this can put you in the right direction as to what is going wrong

**Comment by leoskvl** [comment]
@NikhilBansal21 thanks! have you experienced this? I'm getting this "No such host is known" error message.
![image](https://user-images.githubusercontent.com/13193576/61509438-11c0c700-aa21-11e9-8817-7153e0f952c3.png)

**Comment by NikhilBansal21** [comment]
@leoskvl  follow this - https://forums.asp.net/t/1855430.aspx?How+to+resolve+No+such+host+is+known+ 
mayb be this can resolve your issue

**Comment by NikhilBansal21** [comment]
solved this issue, i was providing full url in app_settings.json ,
