### ISSUE TITLE
client.clientAuthorizations is null

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder-Samples#191]
SDK Platform
Node.js

URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLine

Problem Description
```
Error initializing DirectLine client TypeError: Cannot read property 'add' of undefined
    at D:\bots\zupcoin test\twitter\directline_client.js:23:36
    at tryCatcher (D:\bots\zupcoin test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Unhandled rejection TypeError: Cannot read property 'Conversations' of undefined
    at D:\bots\zupcoin test\twitter\directline_client.js:32:11
    at tryCatcher (D:\bots\zupcoin test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```
I am trying to run the node.js botframework directline sample as it is, i added my directline secret but i am still getting this error.

**Comment by an0o0nym** [comment]
Make sure you are using `swagger-client ^2.1.18`. Or change your code accordingly to be compatible with newer version.

I have run `npm i swagger-client` which installed version 3.x. It turned out that there were [major changes from the 2.x release](https://github.com/swagger-api/swagger-js/blob/master/docs/MIGRATION_2_X.md).

I hope it helps in some way.

**Comment by EricDahlvang** [comment]
core-DirectLine can now be found here: https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/Node/core-DirectLine and it uses ^2.1.18 and works as expected
