### ISSUE TITLE
AttachmentBot failes to upload file

### ISSUE THREAD

**Issue by helenali19** [microsoft/BotBuilder-Samples#2061]
## Sample information
1. Sample type: BotBuilder-Samples/samples
2. Sample language: dotnetcore
3. Sample name: AttachmentsBot

## Describe the bug
GetUploadedAttachmentAsync throws exception: "Operation returned an invalid status code 'NotFound'" 

## To Reproduce
1. Reply option 3 to AttachmentBot
2. AttachmentBot replies message "Sorry, it looks like something went wrong."

## Expected behavior
The attached file "architecture-resize.png" will be uploaded successfully.

## Additional context

[bug]

**Comment by jwiley84** [comment]
Are you using sample #15? Because there are some extra steps needed in order to upload files to teams. This is outline in sample #56 (Teams-File-Upload).

**Comment by mindncz** [comment]
Yes, I was using sample #15. Sample #56 used cards to ask user to Accet/Reject the attachment which works in my environment. However, I want to attach a file with message directly like what #15 does. 

This is the manifest I used.
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
    "manifestVersion": "1.5",
    "version": "4.0",
    "id": "*****",
    "packageName": "com.microsoft.teams.fileupload",
    "developer": {
        "name": "mindcz",
        "websiteUrl": "https://****.azurewebsites.net",
        "privacyUrl": "https://****.azurewebsites.net/privacy",
        "termsOfUseUrl": "https://****.azurewebsites.net/termsofuse"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "***",
        "full": "***"
    },
    "description": {
        "short": "Ask *** bot",
        "full": "*** bot will give you info "
    },
    "accentColor": "#FFFFFF",
    "bots": [
        {
            "botId": "********",
            "scopes": [
                "personal",
                "team",
                "groupchat"
            ],
            "supportsFiles": true
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [ "*.azurewebsites.net"]
}

The code is exactly the same as example #15.

**Comment by jwiley84** [comment]
Alright, let me see if I can repro this for you.

**Comment by vishwacsena** [comment]
@jwiley84 any update?

**Comment by jwiley84** [comment]
I am able to repro this, it's only happening in Teams, attempting to track down the cause.

**Comment by jwiley84** [comment]
There's something in the following code it doesn't like (my debugger is acting up, so I'm going line by line):

```
var response = await attachments.Client.Conversations.UploadAttachmentAsync(
    conversationId,
    new AttachmentData
    {
        Name = @"Resources\architecture-resize.png",
        OriginalBase64 = File.ReadAllBytes(imagePath),
        Type = "image/png",
    });
```

It's kicking back the following stacktrace:

```
fail: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      [OnTurnError] unhandled error : One or more errors occurred. (Operation returned an invalid status code 'NotFound')
System.AggregateException: One or more errors occurred. (Operation returned an invalid status code 'NotFound') ---> Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Bot.Connector.Conversations.UploadAttachmentWithHttpMessagesAsync(String conversationId, AttachmentData attachmentUpload, Dictionary`2 customHeaders, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Connector\Conversations.cs:line 2115
   at Microsoft.Bot.Connector.ConversationsExtensions.UploadAttachmentAsync(IConversations operations, String conversationId, AttachmentData attachmentUpload, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Connector\ConversationsExtensions.cs:line 428
   at Microsoft.BotBuilderSamples.AttachmentsBot.GetUploadedAttachmentAsync(ITurnContext turnContext, String serviceUrl, String conversationId) in C:\Users\Jessi\botwork\BotBuilder-Samples-122719\samples\csharp_dotnetcore\15.handling-attachments\Bots\AttachmentsBot.cs:line 201
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.BotBuilderSamples.AttachmentsBot.HandleOutgoingAttachment(ITurnContext turnContext, IMessageActivity activity) in C:\Users\Jessi\botwork\BotBuilder-Samples-122719\samples\csharp_dotnetcore\15.handling-attachments\Bots\AttachmentsBot.cs:line 118
   at Microsoft.BotBuilderSamples.AttachmentsBot.ProcessInput(ITurnContext turnContext) in C:\Users\Jessi\botwork\BotBuilder-Samples-122719\samples\csharp_dotnetcore\15.handling-attachments\Bots\AttachmentsBot.cs:line 92
   at Microsoft.BotBuilderSamples.AttachmentsBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in C:\Users\Jessi\botwork\BotBuilder-Samples-122719\samples\csharp_dotnetcore\15.handling-attachments\Bots\AttachmentsBot.cs:line 32
   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 1218
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 200
---> (Inner Exception #0) Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Bot.Connector.Conversations.UploadAttachmentWithHttpMessagesAsync(String conversationId, AttachmentData attachmentUpload, Dictionary`2 customHeaders, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Connector\Conversations.cs:line 2115
   at Microsoft.Bot.Connector.ConversationsExtensions.UploadAttachmentAsync(IConversations operations, String conversationId, AttachmentData attachmentUpload, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Connector\ConversationsExtensions.cs:line 428
   at Microsoft.BotBuilderSamples.AttachmentsBot.GetUploadedAttachmentAsync(ITurnContext turnContext, String serviceUrl, String conversationId) in C:\Users\Jessi\botwork\BotBuilder-Samples-122719\samples\csharp_dotnetcore\15.handling-attachments\Bots\AttachmentsBot.cs:line 201<---
```

**Comment by mindncz** [comment]
Is this an example issue or SDK issue?

**Comment by jwiley84** [comment]
Further debugging has show that this particular error is occurring in every test I run EXCEPT the emulator. This option does not work while ngrok'd into Teams, Facebook or webchat, or in a deployed bot using the 'Test in Webchat' feature. Escalating.

**Comment by CoHealer** [comment]
Adding @EricDahlvang to assist.

**Comment by EricDahlvang** [comment]
Hi @mindncz 

I don't think Option 3 of Sample 15 is going to work on Teams, since the Teams channel requires consent to upload files.  Sample 56 is for Teams files, and demonstrates the FileConsentCard.

However, I did test out Option 3 on WebChat and DirectLine where this should work as expected.  We have escalated this issue internally.  Thank you for reporting.

**Comment by mindncz** [comment]
Hi @EricDahlvang 

Thanks for the reply.

As every member belong to a Team could upload files to Teams channel via Teams desktop client or web without any consent, is the content required to upload files only apply to bots? And what's the design reason behind this, just want to better understand it.
