### ISSUE TITLE
Language Generation External Markdown Links broken

### ISSUE THREAD

**Issue by hhasenauer** [microsoft/BotBuilder-Samples#2181]
## Sample information
1. Sample type: Language Generation
2. Sample language: dotnetcore
3. Sample name: Language Generation Preview

## Describe the bug
When using a standard markdown link in the .lg files e.g. \[test](https://google.com), the language generation throws an exception:
```
 at Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine.AddFiles(IEnumerable`1 filePaths, ImportResolverDelegate importResolver)
Unhandled exception. System.Exception: [Error] line 11:0 - line 11:199: source: /Users/x/Documents/source/x-bot/x/Responses/MainResponses.lg. error message: hier does not have an evaluator, it's not a built-in function or a customized function in template reference `hier`
   at Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine.RunStaticCheck(List`1 templates)
   at Microsoft.Bot.Builder.Solutions.Responses.LocaleTemplateEngineManager..ctor(Dictionary`2 localeLGFiles, String fallbackLocale)
   at x.Startup.ConfigureServices(IServiceCollection services) in /Users/x/Documents/source/x-bot/x/Startup.cs:line 133
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at x.Program.BuildWebHost(String[] args) in /Users/x/Documents/source/x-bot/x/Program.cs:line 15
   at x(String[] args) in /Users/x/Documents/source/x-bot/x/Program.cs:line 11
```

## To Reproduce
See above

## Expected behavior
A standard markdown link is rendered in the web chat.

**Comment by dmvtech** [comment]
hi @hhasenauer 

Can you share the LG?

To clarify, you are using a link in a text response? or are you referring to 
[Importing external references](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/lg-file-format.md#importing-external-references)?

I just tested a link in a template:
```
# Greeting
- Hi
- Hello. Please go to [here](https://www.microsoft.com)
```

And it worked fine. 

Also, make sure you are using the most recent nightly builds. I'm using [4.8.0-preview-200211-105347](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.LanguageGeneration/4.8.0-preview-200211-105347)

**Comment by dmvtech** [comment]
@hhasenauer Let us know if you still need any assistance on this one. I'm closing for now assuming you have it resolved. Please reopen or comment if that is not the case.
