### ISSUE TITLE
TeamsInfo.get_member returns  Operation returned an invalid status code 'Not Found'

### ISSUE THREAD

**Issue by aravindtrue** [microsoft/BotBuilder-Samples#2320]
1. Sample type: BotBuilder-Samples/samples/python/03.welcome-user/
2. Sample language: python
3. Sample name: welcome-user

## Describe the bug
I wanted to get the user identity so, I am using the TeamsInfo class by following this documentation,
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=python#get-single-member-details

But it returns, `Operation returned an invalid status code 'Not Found'`

## To Reproduce
1. Clone BotBuilder-Samples/samples/python/03.welcome-user/
2. Open welcome_user_bot.py
3. Add the below line under on_mesage_activity handler,
member = await TeamsInfo.get_member(turn_context, turn_context.activity.from_property.id)
print(member.name, member.id)
4. Run the app, open Bot Framework emulator and send a message

## Expected behavior
Print the member details like id, name, email, AAD id, etc.

[bug]
```
clientActivityID is not a known attribute of class <class 'botbuilder.schema.teams._models_py3.TeamsChannelData'> and will be ignored
clientTimestamp is not a known attribute of class <class 'botbuilder.schema.teams._models_py3.TeamsChannelData'> and will be ignored

 [on_turn_error] unhandled error: Operation returned an invalid status code 'Not Found'
Traceback (most recent call last):
  File "/Users/sample/.virtualenvs/welcome-bot/lib/python3.8/site-packages/botbuilder/core/bot_adapter.py", line 109, in run_pipeline
    return await self._middleware.receive_activity_with_status(
  File "/Users/sample/.virtualenvs/welcome-bot/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
  File "/Users/sample/.virtualenvs/welcome-bot/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
  File "/Users/sample/work-python/welcome-bot/bots/welcome_user_bot.py", line 41, in on_turn
    await super().on_turn(turn_context)
  File "/Users/sample/.virtualenvs/welcome-bot/lib/python3.8/site-packages/botbuilder/core/activity_handler.py", line 64, in on_turn
    await self.on_message_activity(turn_context)
  File "/Users/sample/work-python/welcome-bot/bots/welcome_user_bot.py", line 86, in on_message_activity
    member = await TeamsInfo.get_member(turn_context, turn_context.activity.from_property.id)
  File "/Users/sample/.virtualenvs/welcome-bot/lib/python3.8/site-packages/botbuilder/core/teams/teams_info.py", line 175, in get_member
    return await TeamsInfo._get_member(
  File "/Users/sample/.virtualenvs/welcome-bot/lib/python3.8/site-packages/botbuilder/core/teams/teams_info.py", line 264, in _get_member
    member: TeamsChannelAccount = await connector_client.conversations.get_conversation_member(
  File "/Users/sample/.virtualenvs/welcome-bot/lib/python3.8/site-packages/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 735, in get_conversation_member
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema._models_py3.ErrorResponseException: Operation returned an invalid status code 'Not Found'
Datetime with no tzinfo will be considered UTC.
```

**Comment by Virtual-Josh** [comment]
Hi @aravindtrue,

This is error is somewhat of a red herring. The `TeamsInfo` class is designed to facilitate interactions for bots within Microsoft Teams. It's not intended for the emulator. If you want to get the information of the person who just joined you need to look at the `on_members_added_activity`. Each `member` object has the name, id, and other properties you'd be interested in. 

I'll make a task to look into a way of cleaning up the error so it's better.

**Comment by aravindtrue** [comment]
Hi @Virtual-Josh, Thank you so much for the quick response! Is there any other way to store user information other than id in the emulator?

**Comment by Virtual-Josh** [comment]
There are many ways to store information with the bot framework. If you want to see how an list can be used you can view the bot [here](https://github.com/microsoft/botbuilder-python/tree/master/scenarios/activity-update-and-delete). 

If you want deeper reading on the topic you can look [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0).
