### ISSUE TITLE
Ticks: Date is not standard ISO format

### ISSUE THREAD

**Issue by VMey** [microsoft/BotBuilder-Samples#2349]
Steps to reproduce:
1. Ensure a date is formatted properly according to standards using: formatDateTime(utcNow(), 'yyyy-MM-ddTHH:mm:ss')
2. Attempt to get ticks from this date: ticks(formatDateTime(utcNow(), 'yyyy-MM-ddTHH:mm:ss'))

Expected result: Receive ticks for utcNow()
Actual Result: Exception: 2020-04-28T03:19:03 is not standard ISO format

Full message: 2020-04-28T03:19:03 is not standard ISO format.[f3a1d41c-4394-4010-8bc6-a10a503af210]  Error occurred when evaluating '-```Ticks: today ${ticks(formatDateTime(dialog.today, 'yyyy-MM-ddTHH:mm:ss'))}
Ticks: 1 year from today:
${ticks(formatDateTime(dialog.todayplusoneyear, 'yyyy-MM-ddTHH:mm:ss'))}```'.  

Handle user input failed with exception in 4822 ms. Exception: System.Exception: 2020-04-28T03:19:03 is not standard ISO format.[f3a1d41c-4394-4010-8bc6-a10a503af210]  Error occurred when evaluating '-```Ticks: today ${ticks(formatDateTime(dialog.today, 'yyyy-MM-ddTHH:mm:ss'))}
Ticks: 1 year from today:
${ticks(formatDateTime(dialog.todayplusoneyear, 'yyyy-MM-ddTHH:mm:ss'))}```'. 
   at Microsoft.Bot.Builder.LanguageGeneration.Evaluator.EvalExpression(String exp, ParserRuleContext context, String errorPrefix)
   at Microsoft.Bot.Builder.LanguageGeneration.Evaluator.VisitNormalTemplateString(NormalTemplateStringContext context)
   at Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalTemplateStringContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Bot.Builder.LanguageGeneration.Evaluator.VisitNormalTemplateBody(NormalTemplateBodyContext context)
   at Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalTemplateBodyContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Bot.Builder.LanguageGeneration.Evaluator.VisitNormalBody(NormalBodyContext context)
   at Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalBodyContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Bot.Builder.LanguageGeneration.Evaluator.VisitTemplateDefinition(TemplateDefinitionContext context)
   at Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.TemplateDefinitionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Bot.Builder.LanguageGeneration.Evaluator.EvaluateTemplate(String inputTemplateName, Object scope)
   at Microsoft.Bot.Builder.LanguageGeneration.Templates.Evaluate(String templateName, Object scope)
   at Microsoft.Bot.Builder.LanguageGeneration.Templates.EvaluateText(String text, Object scope)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Generators.TemplateEngineLanguageGenerator.Generate(ITurnContext turnContext, String template, Object data)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.ActivityTemplate.BindToData(ITurnContext context, Object data)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SendActivity.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SetProperty.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SetProperty.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SendActivity.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SendActivity.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnEndOfActionsAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Deloitte.Slate.Bot.Managers.Services.AdaptiveDialogs.CustomTypes.HttpRequestExtended.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken) in F:\agent\_work\2\s\SlateBE\Deloitte.Slate.Bot.Managers\Services\AdaptiveDialogs\CustomTypes\HttpRequestExtended.cs:line 203
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellat

**Comment by vitaliygor** [comment]
Standart ISO format for adaptive dialogs is yyyy-MM-ddTHH:mm:ss.fffZ
