### ISSUE TITLE
[Node] Sample search bot (RealEstate) with different azure search service returns "TypeError: Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by ptrickney** [Microsoft/BotBuilder-Samples#236]
Bot:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/demo-Search 

### Problem Description
I was trying to recreate the RealEstateBot with my azure search service connected with my azure SQL database, but when I change the serviceName, key, and index in the app.js file (plus the url in azure-search.js) I get the following error:

TypeError: Cannot read property 'value' of undefined
    at Request._callback (D:\home\site\wwwroot\SearchProviders\azure-search.js:42:47)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Note: 
I had it work successfully with the sample search service. 
My search service index works in the search explorer.
I'm working in the azure portal with the Bot Emulator on my desktop.

**Comment by ptrickney** [comment]
I was a bit dumb, it's just a settings issue.

Make sure to have the CORS option on the index set to allowed.
