### ISSUE TITLE
Getting 401 even when calling MicrosoftAppCredentials.trustServiceUrl()

### ISSUE THREAD

**Issue by manutero** [microsoft/BotBuilder-Samples#2462]
## Sample information

1. Sample type: `samples`
2. Sample language: `nodejs`
3. Sample name: `16.proactive-messages`

👉 https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/16.proactive-messages/index.js

## Describe the bug

Getting `401: Unauthorized` error when trying to send proactive activity

**note**: Added the call to `trustServiceUrl()` as the doc says:
 
```diff
         // If you encounter permission-related errors when sending this message, see
         // https://aka.ms/BotTrustServiceUrl
+        MicrosoftAppCredentials.trustServiceUrl(turnContext.activity.serviceUrl);
         await turnContext.sendActivity('proactive hello');
``` 

Rising error: 

```log
 RestError: Authorization has been denied for this request.
     at new RestError (/home/site/wwwroot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1397:28)
     at /home/site/wwwroot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1849:37
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async createThread (/home/site/wwwroot/src/bot-features/create-thread.js:26:7)
     at async Object.startThread (/home/site/wwwroot/src/bot.js:199:31)
     at async /home/site/wwwroot/index.js:77:31 {
   code: undefined,
   statusCode: 401,
   request: WebResource {
     streamResponseBody: false,
     url: 'https://smba.trafficmanager.net/emea/v3/conversations',
     method: 'POST',
     headers: HttpHeaders { _headersMap: [Object] },
     body: '{"isGroup":true,"activity":{"type":"message","text":"hi","inputHint":"acceptingInput"},"channelData":{"channel":{"id":"msteams"}}}',
     query: undefined,
     formData: undefined,
     withCredentials: false,
     abortSignal: undefined,
     timeout: 0,
     onUploadProgress: undefined,
     onDownloadProgress: undefined,
     operationSpec: {
       httpMethod: 'POST',
       path: 'v3/conversations',
       requestBody: [Object],
       responses: [Object],
       serializer: [Serializer]
     }
   },
   response: {
     body: '{"message":"Authorization has been denied for this request."}',
     headers: HttpHeaders { _headersMap: [Object] },
     status: 401
   },
   body: { message: 'Authorization has been denied for this request.' }
 }
```

## To Reproduce
1. Go to Microsoft Teams and upload the bot
2. Mention the bot, it will save the conversation on db
3. ⚠️ *REBOOT* the bot (for instance uploading a new version `az webapp deployment source config-zip ...`)
4. HTTP request to '/api/notify'
5. The Unauthorized error rises 

## Expected behavior
The bot is still able to send proactive messages even when it has restarted. 
**Note**: once I have reboot the bot, if I speak again to it (for instance in a private 1:1 conversation) then IT WILL be able to send proactive messages. 

## Additional context

⚠️ **important**: I've modified the sample a bit since I'm storing the conversation references in Azure Cosmos db instead of keeping them in memory. Since I've modified the original code, I wasn't sure if opening this ticket or asking this on SO. please let me know if you consider this is inappropriate.

This is the document I'm storing in db: 

```
{
    "xxx": {
        "activityId": "yyy",
        "user": {
            "id": "zzz",
            "name": "Jhon Doe",
            "aadObjectId": "xxx"
        },
        "bot": {
            "id": "xxx",
            "name": "yyy"
        },
        "conversation": {
            "isGroup": true,
            "conversationType": "channel",
            "tenantId": "zzz",
            "id": "xxx"
        },
        "channelId": "msteams",
        "serviceUrl": "https://smba.trafficmanager.net/emea/"
    }
}
```

`MicrosoftAppCredentials.trustServiceUrl(context.activity.serviceUrl);` is being called with ` "https://smba.trafficmanager.net/emea/"`

[bug]

**Comment by stevkan** [comment]
@manutero,

You mention referencing a doc in your post when setting up your `trustServiceUrl()`. Which doc are you referring to?
Can you provide the code you are using for implementing Cosmos db in your bot?
Are you running this bot locally or from a production state (i.e. deployed on Azure)?
Which version of BotBuilder are you running?

**Comment by manutero** [comment]
Hi @stevkan, 
first thanks for the support. 

1. [Doc](https://github.com/microsoft/BotBuilder-Samples/issues/2462)
> you must manually add the serviceUrl to the list of trusted host names by using `MicrosoftAppCredentials.trustServiceUrl();`

2. Connection to Cosmos db:

```js
const createStorage = () => {
  const storage = new CosmosDbPartitionedStorage({
        cosmosDbEndpoint: process.env.MicrosoftCosmosDbEndpoint,
        authKey: process.env.MicrosoftCosmosDbAuthKey,
        databaseId: process.env.MicrosoftCosmosDbName,
        containerId: process.env.MicrosoftCommosDbContainer,
        compatibilityMode: false,
      });
  console.info(
    `[STARTUP] connected to storage (connectToCosmosDb: ${!useMemory})`
  );
  return storage;
};
```

```js
const saveConversationRef = async (context, storage) => {
  const storeItems = await storage.read([CONVERSATION_KEY]);
  const collection = storeItems[CONVERSATION_KEY];
  if (typeof collection === "undefined") {
    storeItems[CONVERSATION_KEY] = {};
  }
  
  const conversationId = context.activity.conversation.id;
  const conversationRef = TurnContext.getConversationReference(
    context.activity
  );
  storeItems[CONVERSATION_KEY][conversationId] = conversationRef;
  
  await storage.write(storeItems);
};
```

```js
const loadConversationRefs = async (storage) => {
  try {
    const storeItems = await storage.read([CONVERSATION_KEY]);
    return storeItems[CONVERSATION_KEY] || {};
  } catch (err) {
    console.error(err);
    return undefined;
  }
};
```

3. The bot is deployed on Azure and works fine, except that when I restart it, it won't be able to post messages **until** I speak to it. The sequence is the following:

 - Restart bot (for instance when deploying code)
 - request to `/api/notify`
 - 401 ERROR
 - ok, let's talk to it in private (the message doesn't matter)
 - request to `/api/notify` -> 👍

4. From the `package.json`:

```json
  "dependencies": {
        "botbuilder": "~4.7.0",
        "botbuilder-azure": "~4.8.0",
        "botframework-connector": "^4.8.0",
        "dotenv": "^8.2.0",
        "restify": "~8.4.0"
    }
```

**Comment by manutero** [comment]
from `npm list --depth=0`

```
├── botbuilder@4.7.2
├── botbuilder-azure@4.8.0
├── botframework-connector@4.8.0
```

**Comment by vishwacsena** [comment]
@stevkan can you take a look and provide an update?

**Comment by stevkan** [comment]
@manutero, I've been unsuccessfully trying to replicate your issue when I just noticed that you are calling `adapter.continueConversation()` instead of calling `adapter.getConversationReference()`. In that light, it makes sense that the bot would error out when you stop and restart the service as the bot doesn't have an already established conversation.

In the **57.teams-conversation-bot**, you can see [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/57.teams-conversation-bot/bots/teamsConversationBot.js#L155) that a proactive message is being generated and sent out to all team members, irrespective of any conversation having already occurred.

Try using the above sample as a model for setting up the `/api/notify` proactive message call and let me know what success you have.

**Comment by manutero** [comment]
thanks @stevkan , will trace back this hint :ok:

**Comment by stevkan** [comment]
Closing as resolved. If the issue persists, please feel free to reopen.
