### ISSUE TITLE
Error on python sample 54: got multiple values for keyword argument 'type'

### ISSUE THREAD

**Issue by masphei** [microsoft/BotBuilder-Samples#2640]
## Describe the bug
I got error on fetching module while trying on this python sample codes
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/54.teams-task-module

## To Reproduce
1. python app.py in python sample code number 54
2. Say something to the Bot
3. Click "Adaptive Card" on the Bot response

## Expected behavior
It shows the Card correctly

## Console Output
 [on_turn_error] unhandled error: __init__() got multiple values for keyword argument 'type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/botbuilder/core/bot_adapter.py", line 109, in run_pipeline
    return await self._middleware.receive_activity_with_status(
  File "/usr/local/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
  File "/usr/local/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
  File "/usr/local/lib/python3.8/site-packages/botbuilder/core/activity_handler.py", line 76, in on_turn
    invoke_response = await self.on_invoke_activity(turn_context)
  File "/usr/local/lib/python3.8/site-packages/botbuilder/core/teams/teams_activity_handler.py", line 133, in on_invoke_activity
    await self.on_teams_task_module_fetch(
  File "/Users/alfianramadhan/Projects/Accellion/botbuilder-samples/samples/python/54.teams-task-module/bots/teams_task_module_bot.py", line 58, in on_teams_task_module_fetch
    continue_response = TaskModuleContinueResponse(type="continue", value=task_info)
  File "/usr/local/lib/python3.8/site-packages/botbuilder/schema/teams/_models_py3.py", line 1618, in __init__
    super(TaskModuleContinueResponse, self).__init__(type="continue", **kwargs)
TypeError: __init__() got multiple values for keyword argument 'type'

## Screenshots
![image](https://user-images.githubusercontent.com/5512461/89138880-38d43300-d567-11ea-8a24-e87fd4b7b307.png)

## Additional context
In Javascript sample codes it works fine. But in Python sample codes it does not work.

[bug]

**Comment by jwiley84** [comment]
Thank you for reporting this! I'll dig down into it today and get an answer for your and a fix for the sample!

**Comment by jwiley84** [comment]
Just wanted to give a heads up for tracking. I was able to repro this, and I'm working on figuring  out the root cause this morning! Thank you for your patience!

**Comment by jwiley84** [comment]
Note for self: this is also occurring in the sample 53 (Teams Messaging Extension Action Preview)

**Comment by jwiley84** [comment]
Further notes: For sample 54, this only occurs when using `py app.py` in a command line for startup, but does not occur when starting up the sample using VSCode

**Comment by jwiley84** [comment]
My VSC was pulling from local files I'd forgotten about. 

This does not occur in 4.8.0, but does occur with the 4.9.0 and 4.10.0 packages.

**Comment by jwiley84** [comment]
@masphei Thank you for your patience on this. Now that I've narrowed it down a bit, I need to to a bit more digging to try to track down where this is coming from, and get a fix out soon.

**Comment by Josverl** [comment]
I'm running into the same issue in .45 the task module. 

it looks like the offending line is :  
``` python
        continue_response = TaskModuleContinueResponse(type="continue", value=task_info)
```
which does not match the function parameter definition as I read it, ( but note that VSCode's Intellisense does not resolve the function definition either, so there appears to be a secondary issue here as well ) 

the functions is defined as : 
``` python 
class TaskModuleContinueResponse(TaskModuleResponseBase):
    """Task Module Response with continue action.

    :param value: The JSON for the Adaptive card to appear in the task module.
    :type value: ~botframework.connector.teams.models.TaskModuleTaskInfo
    """

    _attribute_map = {
        "type": {"key": "type", "type": "str"},
        "value": {"key": "value", "type": "TaskModuleTaskInfo"},
    }

    def __init__(self, *, value=None, **kwargs) -> None:
        super(TaskModuleContinueResponse, self).__init__(type="continue", **kwargs)
        self.value = value
```
Error:

I think that the **kwargs lead to a duplication of the `type` parameter when this is also provided as a parameter to `TaskModuleContinueResponse`, hence the error : **`TypeError: init() got multiple values for keyword argument 'type'`**
[ref: SO](https://stackoverflow.com/questions/48731490/multiple-values-for-keyword-argument-when-using-kwargs)

a similar issue is with line:
``` python
message_response = TaskModuleMessageResponse(type="message", value="Thanks!")
```

**corrected sample:**
below is a simple correction to the sample,

``` python 
#line 58
        continue_response = TaskModuleContinueResponse( value=task_info)
#line 70
        message_response = TaskModuleMessageResponse( value="Thanks!")
```

works like a charm.

Still : it seems sensible to perform additional parameter check on these function to make them more robust in accepting parameters to make the SDK more robust.

**Comment by jwiley84** [comment]
Thank you for these PRs. I'll reach out the the Python code owner today to get them reviewed soon.

**Comment by tdurnford** [comment]
@axelsrz Can you chime in on this?
