### ISSUE TITLE
Python Skill Sample doesn't work

### ISSUE THREAD

**Issue by winffee** [microsoft/BotBuilder-Samples#2877]
## Sample information
1. Sample type: [\samples\python\80.skills-simple-bot-to-bot]
2. Sample language: [python]
3. Sample name: <echo-skill-bot>,<simple-root-bot>

## Describe the bug
Running python simple-bot-to-bot Echo Skill on emulator, added ms app id and password for root bot and skill bot, got error from skill bot:

Tacktrace:
```
[on_turn_error] unhandled error: Cannot deserialize content-type: text/plain
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_adapter.py", line 128, in run_pipeline
    context, callback
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status     
    return await self.receive_activity_internal(context, callback)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal        
    return await callback(context)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\activity_handler.py", line 68, in on_turn
    await self.on_message_activity(turn_context)
  File "d:\WorkingFolder\2020_10\BotBuilderSample\samples\python\80.skills-simple-bot-to-bot\echo-skill-bot\bots\echo_bot.py", line 21, in on_message_activity
    MessageFactory.text(f"Echo (python): {turn_context.activity.text}")
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 170, in send_activity
    result = await self.send_activities([activity_or_text])
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 217, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 295, in _emit
    return await logic
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 212, in logic
    responses = await self.adapter.send_activities(self, output)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 714, in send_activities
    activity.conversation.id, activity.reply_to_id, activity
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", 
line 529, in reply_to_activity
    request, stream=False, **operation_config
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_requests.py", line 106, in send
    return await self.next.send(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 84, in send
    self._policy.on_response(request, response, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 252, in on_response
    http_response.headers
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 226, in deserialize_from_http_generics       
    return cls.deserialize_from_text(body_bytes, content_type)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain

 Exception caught on _send_error_message : Cannot deserialize content-type: text/plain
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_adapter.py", line 128, in run_pipeline
    context, callback
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status     
    return await self.receive_activity_internal(context, callback)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal        
    return await callback(context)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\activity_handler.py", line 68, in on_turn
    await self.on_message_activity(turn_context)
  File "d:\WorkingFolder\2020_10\BotBuilderSample\samples\python\80.skills-simple-bot-to-bot\echo-skill-bot\bots\echo_bot.py", line 21, in on_message_activity
    MessageFactory.text(f"Echo (python): {turn_context.activity.text}")
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 170, in send_activity
    result = await self.send_activities([activity_or_text])
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 217, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 295, in _emit
    return await logic
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 212, in logic
    responses = await self.adapter.send_activities(self, output)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 714, in send_activities
    activity.conversation.id, activity.reply_to_id, activity
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", 
line 529, in reply_to_activity
    request, stream=False, **operation_config
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_requests.py", line 106, in send
    return await self.next.send(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 84, in send
    self._policy.on_response(request, response, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 252, in on_response
    http_response.headers
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 226, in deserialize_from_http_generics       
    return cls.deserialize_from_text(body_bytes, content_type)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\WorkingFolder\2020_10\BotBuilderSample\samples\python\80.skills-simple-bot-to-bot\echo-skill-bot\adapter_with_error_handler.py", line 39, in _send_error_message
    await turn_context.send_activity(error_message)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 170, in send_activity
    result = await self.send_activities([activity_or_text])
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 217, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 295, in _emit
    return await logic
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 212, in logic
    responses = await self.adapter.send_activities(self, output)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 714, in send_activities
    activity.conversation.id, activity.reply_to_id, activity
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", 
line 529, in reply_to_activity
    request, stream=False, **operation_config
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_requests.py", line 106, in send
    return await self.next.send(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 84, in send
    self._policy.on_response(request, response, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 252, in on_response
    http_response.headers
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 226, in deserialize_from_http_generics       
    return cls.deserialize_from_text(body_bytes, content_type)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain

 Exception caught on _send_eoc_to_parent : Cannot deserialize content-type: text/plain
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_adapter.py", line 128, in run_pipeline
    context, callback
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status     
    return await self.receive_activity_internal(context, callback)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal        
    return await callback(context)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\activity_handler.py", line 68, in on_turn
    await self.on_message_activity(turn_context)
  File "d:\WorkingFolder\2020_10\BotBuilderSample\samples\python\80.skills-simple-bot-to-bot\echo-skill-bot\bots\echo_bot.py", line 21, in on_message_activity
    MessageFactory.text(f"Echo (python): {turn_context.activity.text}")
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 170, in send_activity
    result = await self.send_activities([activity_or_text])
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 217, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 295, in _emit
    return await logic
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 212, in logic
    responses = await self.adapter.send_activities(self, output)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 714, in send_activities
    activity.conversation.id, activity.reply_to_id, activity
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", 
line 529, in reply_to_activity
    request, stream=False, **operation_config
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_requests.py", line 106, in send
    return await self.next.send(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 84, in send
    self._policy.on_response(request, response, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 252, in on_response
    http_response.headers
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\WorkingFolder\2020_10\BotBuilderSample\samples\python\80.skills-simple-bot-to-bot\echo-skill-bot\adapter_with_error_handler.py", line 71, in _send_eoc_to_parent
    await turn_context.send_activity(end_of_conversation)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 170, in send_activity
    result = await self.send_activities([activity_or_text])
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 217, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 295, in _emit
    return await logic
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\turn_context.py", line 212, in logic
    responses = await self.adapter.send_activities(self, output)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botbuilder\core\bot_framework_adapter.py", line 714, in send_activities
    activity.conversation.id, activity.reply_to_id, activity
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", 
line 529, in reply_to_activity
    request, stream=False, **operation_config
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_requests.py", line 106, in send
    return await self.next.send(request, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\async_abc.py", line 84, in send
    self._policy.on_response(request, response, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 252, in on_response
    http_response.headers
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 226, in deserialize_from_http_generics       
    return cls.deserialize_from_text(body_bytes, content_type)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\msrest\pipeline\universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain
```
Can someone tell me what is wrong?

Thanks in advance.

**Comment by Amrit10737726** [comment]
Summary: I have tested \samples\python\80.skills-simple-bot-to-bot in Python and its working fine.
![Screenshot (6)](https://github.com/microsoft/BotBuilder-Samples/assets/167064182/99e7a8a6-ff55-4a2d-8eae-6200530c39c7)

Steps Taken:
1. Updated echo-skill-bot/config.py with the MicrosoftAppId and MicrosoftAppPassword of the new bot registration.
2. Updated simple-root-bot/config.py with the MicrosoftAppId and MicrosoftAppPassword of the new bot registration.
3. Updated the SKILLS.app_id in simple-root-bot/config.py with the MicrosoftAppId.
4. Add the simple-root-bot MicrosoftAppId to the AllowedCallers comma separated list in echo-skill-bot/config.py.
5. Run Both sample echo-skill-bot and simple-root-bot in separate terminal on VS Code.
6. Test it on emulator by providing MicrosoftAppId and MicrosoftAppPassword.
