### ISSUE TITLE
No module named 'aiohttp' Error while deployment of Bot

### ISSUE THREAD

**Issue by dhruv2103** [microsoft/BotBuilder-Samples#3192]
Hi,  I am facing an error while deploying my bot on Microsoft Azure. 

I have used [QnA Bot Example](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/11.qnamaker)) and created a QnABot. and I am able to run it successfully on my local. So, as it is working now on my local. I want to publish it on azure. I did follow the steps shown in [Bot Framework SDK Documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python).

1. I registered for a new App for OAuth.
2. Deployed ARM Template. (using the same ARM template given with [QnA Bot Example](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/11.qnamaker))
3. and Pushed my code. (Note: I did make sure that app.py and requirements.txt in the same location).

I am successfully able to create the app-service plan, app service, and bot channel registration. 
I am also able to deploy my code using the given commands on [Bot Framework SDK Documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python)

The error which I am facing is that while deployment it is showing an error for "No module found named 'aiohttp'":
![image](https://user-images.githubusercontent.com/36305262/115656822-7ece6280-a353-11eb-84ac-3219c126c331.png)

while I did have 'aiohttp' in my requirements.txt.
![image](https://user-images.githubusercontent.com/36305262/115656974-bfc67700-a353-11eb-9562-2015f882b7f8.png)

I looked online. but everywhere, I found similar steps which I am following. I also looked at ["hello world!" app service deployment](https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash) using python but it is not helping.

I found the same issue on Github at [ModuleNotFoundError: No module named 'aiohttp'](https://github.com/Azure/azure-functions-python-worker/issues/713) but I didn't find any solution there.

can you pls help me find the solution for this?

**Comment by axelsrz** [comment]
Hello @dhruv2103 thanks for submitting the issue. This could be a versioning problem, could you try changing your requirements.txt to 
`aiohttp~=3.6.2`

**Comment by sonnyvan** [comment]
I am not sure what I'm doing wrong but I am following the [quickstart guide](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0) and it worked locally. However, I followed these steps https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp and I am getting the following failure as well:

```
2021-04-30T06:51:55.845393270Z Error: class uri 'aiohttp.worker.GunicornWebWorker' invalid or not found:
2021-04-30T06:51:55.845401070Z
2021-04-30T06:51:55.845405871Z [Traceback (most recent call last):
2021-04-30T06:51:55.845410671Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/util.py", line 99, in load_class
2021-04-30T06:51:55.845415671Z     mod = importlib.import_module('.'.join(components))
2021-04-30T06:51:55.845420372Z   File "/opt/python/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
2021-04-30T06:51:55.845425072Z     return _bootstrap._gcd_import(name[level:], package, level)
2021-04-30T06:51:55.845438973Z   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2021-04-30T06:51:55.845443773Z   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2021-04-30T06:51:55.845448073Z   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
2021-04-30T06:51:55.845452374Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-04-30T06:51:55.845456574Z   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2021-04-30T06:51:55.845460774Z   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2021-04-30T06:51:55.845464974Z   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
2021-04-30T06:51:55.845469075Z ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by dhruv2103** [comment]
@sonnyvan 
For me, it is on same directory... and I tried 5-4 times and once it worked too. but other times, it didn't.....😅

**Comment by jpiabrantes** [comment]
@dhruv2103 I have it on the root directory I am using the same requirements.txt as you and I am still getting this error.
