### ISSUE TITLE
51.teams-messaging-extensions-action fails on startup - Unable to resolve service for type 'System.Net.Http.IHttpClientFactory'

### ISSUE THREAD

**Issue by manr** [microsoft/BotBuilder-Samples#3389]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore
3. Sample name: 51.teams-messaging-extensions-action

## Describe the bug
The bot web app fails on startup due to a missing `services.AddHttpClient()` call in `Startup.cs`.
```
 ---> (Inner Exception #1) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Bot.Builder.IBot Lifetime: Transient ImplementationType: Microsoft.BotBuilderSamples.Bots.TeamsMessagingExtensionsActionBot': Unable to resolve service for type 'System.Net.Http.IHttpClientFactory' while attempting to activate 'Microsoft.BotBuilderSamples.Bots.TeamsMessagingExtensionsActionBot'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'System.Net.Http.IHttpClientFactory' while attempting to activate 'Microsoft.BotBuilderSamples.Bots.TeamsMessagingExtensionsActionBot'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)<---
```

## To Reproduce
1. Go to samples/csharp_dotnetcore/51.teams-messaging-extensions-action
2. Execute `dotnet run`

**Comment by tonyanziano** [comment]
@anusharavindrar can you please verify this when you get back?

**Comment by anusharr** [comment]
@manr, thanks for reporting the issue. I am able to reproduce the error when I try to run the sample. Adding `services.AddHttpClient()` to the `Startup.cs` file fixes the issue. Investigating further and will get a PR out and update the thread accordingly.
