### ISSUE TITLE
Python: aiohttp.web_exceptions.HTTPNotFound: Not Found

### ISSUE THREAD

**Issue by qatrick** [microsoft/BotBuilder-Samples#3772]
## Sample information
1. Sample type: samples/python/02.echo-bot
2. Sample language: python
3. Sample name: 02.echo-bot

## Describe the bug

It comes with 500: Internal Server Error when I attempt to access http://localhost:3978

## To Reproduce
$ python3 -m venv venv
itrs@HKGITDW139891:~/repo/bot2/botbuilder-samples/samples/python/02.echo-bot$ python -V
Python 3.9.13
itrs@HKGITDW139891:~/repo/bot2/botbuilder-samples/samples/python/02.echo-bot$ source venv/bin/activate
(venv) itrs@HKGITDW139891:~/repo/bot2/botbuilder-samples/samples/python/02.echo-bot$ python -V
Python 3.9.13
(venv) itrs@HKGITDW139891:~/repo/bot2/botbuilder-samples/samples/python/02.echo-bot$ pip install -r requirements.txt
...
Installing collected packages: PyJWT, urllib3, typing-extensions, six, pycparser, oauthlib, multidict, jsonpickle, idna, chardet, certifi, attrs, async-timeout, yarl, requests, isodate, cffi, requests-oauthlib, cryptography, aiohttp, msrest, msal, botbuilder-schema, botframework-connector, botframework-streaming, botbuilder-core, botbuilder-integration-aiohttp
Successfully installed PyJWT-1.7.1 aiohttp-3.7.4.post0 async-timeout-3.0.1 attrs-21.4.0 botbuilder-core-4.14.2 botbuilder-integration-aiohttp-4.14.2 botbuilder-schema-4.14.2 botframework-connector-4.14.2 botframework-streaming-4.14.2 certifi-2022.5.18.1 cffi-1.15.0 chardet-4.0.0 cryptography-3.4.8 idna-2.10 isodate-0.6.1 jsonpickle-1.4.2 msal-1.6.0 msrest-0.6.19 multidict-6.0.2 oauthlib-3.2.0 pycparser-2.21 requests-2.25.1 requests-oauthlib-1.3.1 six-1.16.0 typing-extensions-4.2.0 urllib3-1.26.9 yarl-1.4.2
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/home/itrs/repo/bot2/botbuilder-samples/samples/python/02.echo-bot/venv/bin/python3 -m pip install --upgrade pip' command.
$ python app.py
======== Running on http://localhost:3978 ========
(Press CTRL+C to quit)
Traceback (most recent call last):
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/02.echo-bot/venv/lib/python3.9/site-packages/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
    response = await handler(request)
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/02.echo-bot/venv/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 927, in _handle
    raise self._http_exception
aiohttp.web_exceptions.HTTPNotFound: Not Found

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
======== Running on http://localhost:3978 ========
(Press CTRL+C to quit)
Traceback (most recent call last):
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/venv/lib/python3.10/site-packages/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
    response = await handler(request)
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/venv/lib/python3.10/site-packages/aiohttp/web_urldispatcher.py", line 927, in _handle
    raise self._http_exception
aiohttp.web_exceptions.HTTPNotFound: Not Found
^CTraceback (most recent call last):
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/02.echo-bot/app.py", line 88, in <module>
    raise error
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/02.echo-bot/app.py", line 86, in <module>
    web.run_app(APP, host="localhost", port=CONFIG.PORT)
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/venv/lib/python3.10/site-packages/aiohttp/web.py", line 512, in run_app
    _cancel_tasks({main_task}, loop)
  File "/home/itrs/repo/bot2/botbuilder-samples/samples/python/venv/lib/python3.10/site-packages/aiohttp/web.py", line 444, in _cancel_tasks
    asyncio.gather(*to_cancel, loop=loop, return_exceptions=True)
TypeError: gather() got an unexpected keyword argument 'loop'

## Additional context
I tried w different python ver inc. 3.8.3, 3.9.13 and 3.10.5 but seems with the same issue

**Comment by anishprasad01** [comment]
Hi @qatrick,

I attempted to reproduce this issue, and I was unable to. The echo bot ran correctly for me with no 500 errors.

Perhaps you could try something for me. Since we are using python 3, perhaps using `pip3` to install the requirements may prove more successful? Try it using a fresh copy of the sample and let me know if this works for you.

**Comment by rohithq** [comment]
I am having the same issue

**Comment by mvassiliadis** [comment]
Same issue here

**Comment by frankqianms** [comment]
same issue here

**Comment by michalmar** [comment]
same issue
