### ISSUE TITLE
JAVA Sprint - QnA bot can not work of unexpected error: 404

### ISSUE THREAD

**Issue by Tailcloud** [microsoft/BotBuilder-Samples#3820]
Environment: VSCode with JRE1.8 and Maven 3.8.6
Run successfully and returns 202 while connecting with bot emulator ; however, it shows 404 once new messages. Error details as followings,
```

2022-09-01 22:09:17.876  INFO 36068 --- [nio-3978-exec-2] c.microsoft.bot.sample.qnamaker.QnABot   : Calling QnA Maker
2022-09-01 22:09:19.539 ERROR 36068 --- [nio-3978-exec-2] c.m.b.i.AdapterWithErrorHandler          : onTurnError

java.util.concurrent.CompletionException: java.lang.Exception: Unexpected code 404
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1177) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[na:na]
        at com.microsoft.bot.ai.qna.utils.GenerateAnswerUtils.queryQnaService(GenerateAnswerUtils.java:267) ~[bot-ai-qna-4.14.1.jar:4.14.1]
        at com.microsoft.bot.ai.qna.utils.GenerateAnswerUtils.getAnswersRaw(GenerateAnswerUtils.java:132) ~[bot-ai-qna-4.14.1.jar:4.14.1]  
        at com.microsoft.bot.ai.qna.QnAMaker.getAnswersRaw(QnAMaker.java:228) ~[bot-ai-qna-4.14.1.jar:4.14.1]
        at com.microsoft.bot.ai.qna.QnAMaker.getAnswers(QnAMaker.java:184) ~[bot-ai-qna-4.14.1.jar:4.14.1]
        at com.microsoft.bot.ai.qna.QnAMaker.getAnswers(QnAMaker.java:160) ~[bot-ai-qna-4.14.1.jar:4.14.1]
        at com.microsoft.bot.sample.qnamaker.QnABot.onMessageActivity(QnABot.java:41) ~[classes/:na]
        at com.microsoft.bot.builder.ActivityHandler.onTurn(ActivityHandler.java:78) ~[bot-builder-4.14.1.jar:4.14.1]
        at com.microsoft.bot.builder.MiddlewareSet.receiveActivityInternal(MiddlewareSet.java:99) ~[bot-builder-4.14.1.jar:4.14.1]
        at com.microsoft.bot.builder.MiddlewareSet.lambda$receiveActivityInternal$1(MiddlewareSet.java:110) ~[bot-builder-4.14.1.jar:4.14.1]
        at com.microsoft.bot.builder.BotFrameworkAdapter$TenantIdWorkaroundForTeamsMiddleware.onTurn(BotFrameworkAdapter.java:1430) ~[bot-builder-4.14.1.jar:4.14.1]
        at com.microsoft.bot.builder.MiddlewareSet.receiveActivityInternal(MiddlewareSet.java:109) ~[bot-builder-4.14.1.jar:4.14.1]        
        at com.microsoft.bot.builder.MiddlewareSet.receiveActivityInternal(MiddlewareSet.java:74) ~[bot-builder-4.14.1.jar:4.14.1]
        at com.microsoft.bot.builder.MiddlewareSet.receiveActivityWithStatus(MiddlewareSet.java:67) ~[bot-builder-4.14.1.jar:4.14.1]       
        at com.microsoft.bot.builder.BotAdapter.runPipeline(BotAdapter.java:206) ~[bot-builder-4
```.14.1.jar:4.14.1]

**Comment by ramfattah** [comment]
Hi @Tailcloud,

I was not able to reproduce this issue.

#### Enviornment 
* Apache Maven 3.8.6
* IDE: IntelliJ IDEA
* BF Emulator v[4.14.1](https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.14.1)
*  OS: Windows 11

Using Java bot sample [11.qnamaker](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/11.qnamaker), I successfully retrieved answers from QnA KnowledgeBase:
![javaQnABotSample](https://user-images.githubusercontent.com/38049078/188518142-aa8f44ad-c8c1-4905-9eb6-edddc92dbfbb.png)

**Comment by ramfattah** [comment]
Closing due to inactivity, @Tailcloud please re-open if needed.
