### ISSUE TITLE
send message to AU/APAC with error 400,payload is incorrect

### ISSUE THREAD

**Issue by Jeff-Zhang-Github** [microsoft/BotBuilder-Samples#3824]
## Version
springboot

## Describe the bug

`adapter.continueConversation(
                        appId, reference, turnContext -> turnContext
                                .sendActivity(message)
                                .thenApply(resourceResponse -> null)
                );`

when bot send message to AU(https://smba.trafficmanager.net/au/)/APAC(https://smba.trafficmanager.net/apac/) with error 400,payload is incorrect. but rest is normal(https://smba.trafficmanager.net/amer/).

java.util.concurrent.CompletionException: com.microsoft.bot.connector.rest.ErrorResponseException: Status code 400, {"error":{"code":"BadSyntax","message":"Payload is incorrect"}}
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at retrofit2.CompletableFutureCallAdapterFactory$ResponseCallAdapter$2.onResponse(CompletableFutureCallAdapterFactory.java:119)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.microsoft.bot.connector.rest.ErrorResponseException: Status code 400, {"error":{"code":"BadSyntax","message":"Payload is incorrect"}}
        at jdk.internal.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.microsoft.bot.restclient.ServiceResponseBuilder.build(ServiceResponseBuilder.java:118)
        at com.microsoft.bot.connector.rest.RestConversations.replyToActivityDelegate(RestConversations.java:494)
        at com.microsoft.bot.connector.rest.RestConversations.lambda$replyToActivity$5(RestConversations.java:471)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        ... 9 common frames omitted

## converstaion
I didn't change the conversation

{
  "activityId": "activityId",
  "user": {
    "id": "2id",
    "aadObjectId": "aadObjectId"
  },
  "bot": {
    "id": "botId",
    "name": "botName"
  },
  "conversation": {
    "group": false,
    "isGroup": false,
    "conversationType": "personal",
    "tenantId": "tenantId",
    "id": "id"
  },
  "channelId": "msteams",
  "serviceUrl": "https://smba.trafficmanager.net/au/"
}

**Comment by ramfattah** [comment]
Hi @Jeff-Zhang-Github, we are investigating.

**Comment by ramfattah** [comment]
@Jeff-Zhang-Github, Could you please share the steps [to reproduce](https://github.com/microsoft/BotBuilder-Samples/blob/main/.github/ISSUE_TEMPLATE/-samples-bug.md#:~:text=the%20bug%20is.-,To%20Reproduce,-Steps%20to%20reproduce) this issue?

**Comment by Jeff-Zhang-Github** [comment]
Hi,@ramfattah, I updated the issue, and now the service seems normal. It has been restored around 2022-09-13 09:31:04 UTC,Let me know if you find out.

**Comment by hami-sh** [comment]
+1 -- we also experienced this outage in the AU region. 

Any reason why this occurred?

**Comment by Jeff-Zhang-Github** [comment]
This problem occurred again today, around 2022-09-15 08:55UTC, for ten minutes or so, including EMEA and AMER.
