### ISSUE TITLE
NotBeforeError: jwt not active when processing activity

### ISSUE THREAD

**Issue by bmutafov** [microsoft/BotBuilder-Samples#3830]
## Describe the bug
I have a bot that has been working well for years, starting it up locally every few months. Today I am getting a new error, which I have no idea how to resolve:

I have a Nest backend with an endpoint `api/messages` which handles the incoming message requests:
```typescript
@Post('api/messages')
async handleBotMessage(@Req() request: Request, @Res() response: Response): Promise<void> {
    try {
      return await this.botService.adapter.process(request, response, this.botService.run);
    } catch (err) {
      this.logger.error('Error processing activity: ', err.stack);
      throw new InternalServerErrorException('Cannot handle request...');
    }
 }
```

The code for creating the `botService.adapter`:
```typescript
const botFrameworkAuthentication = new ConfigurationBotFrameworkAuthentication({
      MicrosoftAppId: process.env.BOT_APP_ID,
      MicrosoftAppPassword: process.env.BOT_APP_PASSWORD,
      MicrosoftAppType: 'SingleTenant',
      MicrosoftAppTenantId: process.env.TENANT_ID,
} as ConfigurationBotFrameworkAuthenticationOptions);

/** create adapter, which is used by the bot framework to send messages */
this._adapter = new CloudAdapter(botFrameworkAuthentication);
```

I have my `.env` variables set as what I believe to be correct values. Never changed anything and it worked well for at least 2 years.

## Behaviour
```
[Nest] 7743  - 09/28/2022, 9:41:12 AM     LOG [LoggingInterceptor] [/api/messages] --> BotController.handleBotMessage 
Error finding key for token. Available keys: -----BEGIN RSA PUBLIC KEY-----
// some key here which I omitted, if needed I can provide it
-----END RSA PUBLIC KEY-----

JwtTokenExtractor.getIdentity:err! NotBeforeError: jwt not active
    at /home/node_modules/jsonwebtoken/verify.js:143:21
    at getSecret (/home/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/home/node_modules/jsonwebtoken/verify.js:94:10)
    at JwtTokenExtractor.<anonymous> (/home/node_modules/botframework-connector/src/auth/jwtTokenExtractor.ts:158:35)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node_modules/botframework-connector/lib/auth/jwtTokenExtractor.js:12:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  date: 2022-09-29T15:22:24.000Z
}
And nothing happens with the bot response... I searched documentation and issues and did not find anything related to where this issue might be coming from. 
```

## Expected behavior
`bot.run()` function should execute with the respective handlers

**Comment by ramfattah** [comment]
Thank you @bmutafov, we are investigating.

**Comment by ramfattah** [comment]
Hi @bmutafov, 

Are you facing the same issue if using the bot samples from the official [typescript_nodejs](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs) repository?

In sample [05.multi-turn-prompt](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs/05.multi-turn-prompt), the `bot.run()` method seems to looks different from your code:

https://github.com/microsoft/BotBuilder-Samples/blob/b750e9eaf99c0f612c49cfa42e523ad2fc4e6b24/samples/typescript_nodejs/05.multi-turn-prompt/src/index.ts#L78-L82

**Comment by ramfattah** [comment]
closing due to inactivity.

**Comment by bmutafov** [comment]
It actually got fixed by itself, so my best guess it was a Microsoft-related issue, rather than a framework one

**Comment by bmutafov** [comment]
@ramfattah Sorry for the lack of updates before, was on a holiday.

Anyways, today I have the same issue. Nothing has changed since yesterday, when it was working. I downloaded the 05.multi-turn-prompt sample and ran it with the same BotId and TenantId and still getting the same error:

```
Error finding key for token. Available keys: -----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAubfEYu04rUbOZmJj2c8eYHvtsmV6ttGbrvrvCrEJ6mgFpdZACCOJ
EUI7ISZl9Ov97jV/C3JYtOArxGPXbx3cdLIMk7H1Vf/taA6vD0ozDWOPrGOTfaOm
+wEZjq9fNv9Spd7FXo2YKYOmlGSYxweJC7+ZzUoY/zmqd+9QHha9jvVkZ9HfYXuW
aZiEHZSg20cJ+IRMWU6c4sLJgil4J4K3A7UoNwi9VptliGEhzTX5Dft4hYKEnuuz
UioJaZ/54Cq+wctYrnNzSuY7p9tS9vO11JbQxpJNzte6gkREELaOKTOF8TzTW/QC
EcaiqlaTJyELwApS2CehHFUpdQCVrznMPQIDAQAB
-----END RSA PUBLIC KEY-----

JwtTokenExtractor.getIdentity:err! NotBeforeError: jwt not active
    at /home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/jsonwebtoken/verify.js:143:21
    at getSecret (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/jsonwebtoken/verify.js:94:10)
    at JwtTokenExtractor.<anonymous> (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/botframework-connector/lib/auth/jwtTokenExtractor.js:137:54)
    at Generator.next (<anonymous>)
    at fulfilled (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/botframework-connector/lib/auth/jwtTokenExtractor.js:12:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  date: 2022-10-11T13:01:23.000Z
}
Error finding key for token. Available keys: -----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAubfEYu04rUbOZmJj2c8eYHvtsmV6ttGbrvrvCrEJ6mgFpdZACCOJ
EUI7ISZl9Ov97jV/C3JYtOArxGPXbx3cdLIMk7H1Vf/taA6vD0ozDWOPrGOTfaOm
+wEZjq9fNv9Spd7FXo2YKYOmlGSYxweJC7+ZzUoY/zmqd+9QHha9jvVkZ9HfYXuW
aZiEHZSg20cJ+IRMWU6c4sLJgil4J4K3A7UoNwi9VptliGEhzTX5Dft4hYKEnuuz
UioJaZ/54Cq+wctYrnNzSuY7p9tS9vO11JbQxpJNzte6gkREELaOKTOF8TzTW/QC
EcaiqlaTJyELwApS2CehHFUpdQCVrznMPQIDAQAB
-----END RSA PUBLIC KEY-----

JwtTokenExtractor.getIdentity:err! NotBeforeError: jwt not active
    at /home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/jsonwebtoken/verify.js:143:21
    at getSecret (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/jsonwebtoken/verify.js:94:10)
    at JwtTokenExtractor.<anonymous> (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/botframework-connector/lib/auth/jwtTokenExtractor.js:137:54)
    at Generator.next (<anonymous>)
    at fulfilled (/home/Work/botbuilder-samples/samples/typescript_nodejs/05.multi-turn-prompt/node_modules/botframework-connector/lib/auth/jwtTokenExtractor.js:12:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  date: 2022-10-11T13:01:23.000Z
}
```

Should we reopen this ticket?
