### ISSUE TITLE
Java: 07.using-adaptive-cards fails when run

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotBuilder-Samples#3861]
<img width="728" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/1024902/212937695-14dfc131-d868-4689-a774-147a5888460f.png">

**Comment by anishprasad01** [comment]
@tracyboehrer 

I am unable to reproduce this when running Java sample 7 on JDK 11 or JDK 17. The sample runs correctly for me.

**Comment by erquirogasw** [comment]
Hi @tracyboehrer. We weren't able to reproduce the issue using Java JDK 11 or 13. Do you know what version of Java is causing the sample to fail?

**Comment by tracyboehrer** [comment]
@ceciliaavila 

[4:49 AM] Pawan Koshti (Tata Consultancy Services Limi)
Tracy BoehrerI had opened an issue for the Java #07 sample: Java: 07.using-adaptive-cards fails when run · Issue #3861 · microsoft/BotBuilder-Samples (github.com)     The engineers are unable to reproduce this.  Do you have any more info on this?Hi Tracy, We've tried your sample in given step (using Bot Emmulator) it is working fine. But when ever we are testing application in microsoft teams via creating the azure bot and using the ngrok as a tunnel, we are experiencing the issue like below java.util.concurrent.CompletionException: com.microsoft.bot.connector.authentication.AuthenticationException: Invalid AppId passed on token: '967efa97-be2f-4421-8a69-1d3c46ca6069'.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[na:na]   
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687) ~[na:na]       
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[na:na]     
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[na:na]        
        at com.microsoft.bot.connector.authentication.ChannelValidation.lambda$authenticateToken$1(ChannelValidation.java:146) ~[bot-connector-4.14.1.jar!/:4.14.1]
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]      
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[na:na]  
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[na:na] 
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]     
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
Caused by: com.microsoft.bot.connector.authentication.AuthenticationException: Invalid AppId passed on token: '967efa97-be2f-4421-8a69-1d3c46ca6069'.
        at com.microsoft.bot.connector.authentication.ChannelValidation.lambda$null$0(ChannelValidation.java:149) ~[bot-connector-4.14.1.jar!/:4.14.1]
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[na:na]       
        ... 12 common frames omitted We've tested node js sample in Teams via following the above mention steps and it is working fine. As per our understanding it could be the issue with the configuration related to azure bot or from the code side.Could you please share you thoughts.

**Comment by erquirogasw** [comment]
Hi @tracyboehrer. We tested the sample in Teams and it's working fine unless you don't set the credentials in _application.properties_ or execute the `mvn package` command after setting them.

**Comment by ChetanSharma-msft** [comment]
Hello @erquirogasw - We will try in this way and let you know the updates.

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, we think this issue can be closed. We suspect it was a configuration problem and the last activity was in February.
