### ISSUE TITLE
[JS] CoreBot sample cannot start with restify exception 

### ISSUE THREAD

**Issue by luckyBricks** [microsoft/BotBuilder-Samples#3862]
## Sample information
1. Sample type:  **samples**
2. Sample language:  **nodejs** 
3. Sample name: **13.core-bot**

## Describe the bug

With the latest **Node.js LTS v18.13.0**, just following the README steps to run `npm start`, below error call stacks from **restify** detected.

```javascript

D:\Projects\BotBuilder-Samples\samples\javascript_nodejs\13.core-bot\node_modules\restify\lib\request.js:848
    Request.prototype.closed = function closed() {
                             ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (D:\Projects\BotBuilder-Samples\samples\javascript_nodejs\13.core-bot\node_modules\restify\lib\request.js:848:30)
    at Object.<anonymous> (D:\Projects\BotBuilder-Samples\samples\javascript_nodejs\13.core-bot\node_modules\restify\lib\server.js:33:1)       
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\Projects\BotBuilder-Samples\samples\javascript_nodejs\13.core-bot\node_modules\restify\lib\index.js:10:14)       
    at Module._compile (node:internal/modules/cjs/loader:1218:14)

Node.js v18.13.0
```

## To Reproduce
1. Clone the repo
2. Run `npm install` to install dependencies
3. Run `npm start` to start the project

## Expected behavior
The server should start as expected.

## Investigation
It's a known issue for [restify cannot be imported with latest node v18.0.0 nightly: Request.prototype.closed patch clashes with new Readable.closed getter](https://github.com/restify/node-restify/issues/1888)
The problem got resolved by changing **restify** dependency version greater than v10.0.0. 
Other samples using the same library may face the same error.

**Comment by luckyBricks** [comment]
Just noticed the PR#3860 is aim to resolve same problem. https://github.com/microsoft/BotBuilder-Samples/pull/3860
