### ISSUE TITLE
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unable to create call adapter for java.util.concurrent.CompletableFuture<retrofit2.Response<okhttp3.ResponseBody>>

### ISSUE THREAD

**Issue by Jsunny271** [microsoft/BotBuilder-Samples#3964]
Facing this issue since days please help.

ERROR c.m.b.i.AdapterWithErrorHandler - NO_USER onTurnError 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unable to create call adapter for java.util.concurrent.CompletableFuture<retrofit2.Response<okhttp3.ResponseBody>>
   for method ConversationsService.replyToActivity
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.IllegalArgumentException: Unable to create call adapter for java.util.concurrent.CompletableFuture<retrofit2.Response<okhttp3.ResponseBody>>
   for method ConversationsService.replyToActivity
    at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
    at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:234)
    at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:160)
    at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
    at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
    at com.microsoft.bot.connector.rest.$Proxy516.replyToActivity(Unknown Source)
    at com.microsoft.bot.connector.rest.RestConversations.replyToActivity(RestConversations.java:460)
    at com.microsoft.bot.connector.Conversations.replyToActivity(Conversations.java:202)
    at com.microsoft.bot.builder.BotFrameworkAdapter.lambda$sendActivities$5(BotFrameworkAdapter.java:618)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
    ... 5 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for java.util.concurrent.CompletableFuture<retrofit2.Response<okhttp3.ResponseBody>>.
 Tried:
  * retrofit2.DefaultCallAdapterFactory
    at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:237)
    at retrofit2.Retrofit.callAdapter(Retrofit.java:201)
    at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:232)
    ... 13 common frames omitted
Expand (31 lines)

**Comment by tracyboehrer** [comment]
The Java SDK and samples reached end of life November 2023 and are no longer support.  The samples are retrained as a convenience to existing customer for a period.
