### ISSUE TITLE
[ignite] v4 node.js sample basic bot hits a 500 (UnhandledPromiseRejectionWarning) when talking to a local bot with the emulator

### ISSUE THREAD

**Issue by Joseph-Szymanski** [Microsoft/BotBuilder-Samples#400]
Using node version v8.12.0:

- Create a v4 sdk basic bot templated bot (javascript_nodejs\13.basic-bot). 
- Run the bot locally in VS code. 
- Connect to the bot in the emulator
- The emulator fails to send messages to the bot. In the console, I get the following error (full log included):

Launch configuration created based on 'package.json'.
C:\Program Files\nodejs\node.exe --inspect-brk=13035 index.js 
Debugger listening on ws://127.0.0.1:13035/9fb3b6a2-0429-425a-aa4b-b96f41bbbb2d

restify listening to http://[::]:3978

Get the Emulator: https://aka.ms/botframework-emulator

To talk to your bot, open the basic-bot.bot file in the Emulator
BotFrameworkAdapter.processActivity(): 500 ERROR - TypeError: client.pipeline is not a function
(node:11168) UnhandledPromiseRejectionWarning: TypeError: client.pipeline is not a function
    at Conversations.<anonymous> (c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\node_modules\botframework-connector\src\generated\operations\conversations.ts:712:35)
    at Generator.next (<anonymous>)
    at c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:10:12)
    at Conversations.replyToActivityWithHttpOperationResponse (c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:678:16)
    at Conversations.replyToActivity (c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\node_modules\botframework-connector\src\generated\operations\conversations.ts:1675:19)
    at next (c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\src\botFrameworkAdapter.ts:535:62)
    at Promise (c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\src\botFrameworkAdapter.ts:562:13)
    at new Promise (<anonymous>)
(node:11168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sgellock** [comment]
Can you provide the Emulator version you are using to hit this issue?  thanks

**Comment by Joseph-Szymanski** [comment]
4.0.474-nightly (seems to be latest on https://github.com/Microsoft/BotFramework-Emulator/releases)

**Comment by stevengum** [comment]
Note: Original attempts were with Node.js 8.10.0.

Closing as Joe and I were both unable to repro this on my machine and his original machine: we both had Node.js 8.12.0 and NPM 6.4.1 installed and were doing fresh installs of the sample. 

`client.pipeline` refers to `ms-rest-js`, it seems like a bad/newer version was installed when `npm install ms-rest-js` was called (see issue #399).
