### ISSUE TITLE
Echo-bot logs [on_turn_error] unhandled error: 'access_token'

### ISSUE THREAD

**Issue by allanmo79** [microsoft/BotBuilder-Samples#4000]
## Sample information
1. Sample type: samples/python/02.echo-bot
2. Sample language: Python 3.9
3. Sample name: 02.echo-bot

## Describe the bug
Followed guide to deploy samples/python/02.echo-bot for deploying bot to azure (https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot) can get it to run locally if i use `botbuilder-integration-aiohttp==4.14.8` instead of 4.15. 
But keep getting:

```
2024-07-03T15:16:15.6586670Z  [on_turn_error] unhandled error: 'access_token'
2024-07-03T15:16:15.6761941Z Traceback (most recent call last):
2024-07-03T15:16:15.6762440Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/bot_adapter.py", line 174, in run_pipeline
2024-07-03T15:16:15.6762588Z     return await self._middleware.receive_activity_with_status(
2024-07-03T15:16:15.6762638Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/middleware_set.py", line 69, in receive_activity_with_status
2024-07-03T15:16:15.6762669Z     return await self.receive_activity_internal(context, callback)
2024-07-03T15:16:15.6762757Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/middleware_set.py", line 79, in receive_activity_internal
2024-07-03T15:16:15.6762788Z     return await callback(context)
2024-07-03T15:16:15.6762822Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/activity_handler.py", line 70, in on_turn
2024-07-03T15:16:15.6762851Z     await self.on_message_activity(turn_context)
2024-07-03T15:16:15.6762884Z   File "/tmp/8dc9b707c9a6f41/bots/echo_bot.py", line 17, in on_message_activity
2024-07-03T15:16:15.6762916Z     return await turn_context.send_activity(
2024-07-03T15:16:15.6762952Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/turn_context.py", line 173, in send_activity
2024-07-03T15:16:15.6763000Z     result = await self.send_activities([activity_or_text])
2024-07-03T15:16:15.6763036Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/turn_context.py", line 225, in send_activities
2024-07-03T15:16:15.6763067Z     return await self._emit(self._on_send_activities, output, logic())
2024-07-03T15:16:15.6763100Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/turn_context.py", line 303, in _emit
2024-07-03T15:16:15.6763133Z     return await logic
2024-07-03T15:16:15.6763167Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/turn_context.py", line 220, in logic
2024-07-03T15:16:15.6763200Z     responses = await self.adapter.send_activities(self, output)
2024-07-03T15:16:15.6763234Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botbuilder/core/cloud_adapter_base.py", line 93, in send_activities
2024-07-03T15:16:15.6763373Z     response = await connector_client.conversations.reply_to_activity(
2024-07-03T15:16:15.6763412Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 523, in reply_to_activity
2024-07-03T15:16:15.6763442Z     response = await self._client.async_send(
2024-07-03T15:16:15.6763475Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/msrest/async_client.py", line 115, in async_send
2024-07-03T15:16:15.6763506Z     pipeline_response = await self.config.pipeline.run(request, **kwargs)
2024-07-03T15:16:15.6763538Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/msrest/pipeline/async_abc.py", line 159, in run
2024-07-03T15:16:15.6763571Z     return await first_node.send(pipeline_request, **kwargs)  # type: ignore
2024-07-03T15:16:15.6763622Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/msrest/pipeline/async_abc.py", line 79, in send
2024-07-03T15:16:15.6763653Z     response = await self.next.send(request, **kwargs)  # type: ignore
2024-07-03T15:16:15.6763686Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/msrest/pipeline/async_requests.py", line 99, in send
2024-07-03T15:16:15.6763715Z     self._creds.signed_session(session)
2024-07-03T15:16:15.6763749Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botframework/connector/auth/app_credentials.py", line 98, in signed_session
2024-07-03T15:16:15.6772676Z     auth_token = self.get_access_token()
2024-07-03T15:16:15.6772757Z   File "/tmp/8dc9b707c9a6f41/antenv/lib/python3.9/site-packages/botframework/connector/auth/microsoft_app_credentials.py", line 65, in get_access_token
2024-07-03T15:16:15.6772788Z     return auth_token["access_token"]
2024-07-03T15:16:15.6772819Z KeyError: 'access_token'
```

from log stream

## To Reproduce
1. follow guide: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot

## Expected behavior
testing bot using portal "Test in web app"

**Comment by allanmo79** [comment]
Turned out to be related to app not being multitenant https://stackoverflow.com/questions/78221169/single-tenant-teams-bot-authentication-error-missing-access-token
