### ISSUE TITLE
[Docs] Sample code in Docs don't run as provided

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#896]
## Describe the bug
Sample code in Docs don't run as provided, link to runnable sample, samples provided often don't match Doc

## Additional context
Link to docs:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=javascript

https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/04.simple-prompt/index.js

Docs should provide an overview/context, then actionable/runnable code to put the concept into practice.

[bug]

**Comment by JonathanFingold** [comment]
@sgellock The javascript_nodejs\04.simple-prompt does not run following the README instructions. (Does the sample or the README assume that Restify is istalled globally already?)

```text
> npm i && npm start
At line:1 char:7
+ npm i && npm start
+       ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
   ception
    + FullyQualifiedErrorId : InvalidEndOfLine

PS ...\BotBuilder-Samples\samples\javascript_nodejs\04.simple-prompt> npm i
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-node@^8.0.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'simple-prompt-bot'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\npm-cache\_logs\2018-11-12T19_03_40_329Z-debug.log
> npm start

> simple-prompt-bot@1.0.0 start ...\BotBuilder-Samples\samples\javascript_nodejs\04.simple-prompt
> node ./index.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'restify'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\BotBuilder-Samples\samples\javascript_nodejs\04.simple-prompt\index.js:4:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by Kaiqb** [comment]
This sample is no longer referenced in the topic mentioned above.

**Comment by sgellock** [comment]
@Kaiqb @JonathanFingold the sample builds and runs fine for me.  I'm not able to repo the errors above.  I'm running the following:
macOS, 
node v8.12.0
nom v6.4.1

If it persists for you, let me know

**Comment by JonathanFingold** [comment]
FYI, verified that it runs as described for me too now.
